// <auto-generated />
using System;
using Interrapidisimo.Microservices.Api.Student.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Interrapidisimo.Microservices.Api.Student.EntityFramework.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    partial class StudentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Interrapidisimo.Microservices.Api.Student.Entities.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("StudentId", "SubjectId")
                        .IsUnique();

                    b.ToTable("Enrollments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StudentId = 1,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 2,
                            StudentId = 1,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 3,
                            StudentId = 1,
                            SubjectId = 7
                        },
                        new
                        {
                            Id = 4,
                            StudentId = 2,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 5,
                            StudentId = 2,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 6,
                            StudentId = 2,
                            SubjectId = 7
                        },
                        new
                        {
                            Id = 7,
                            StudentId = 3,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 8,
                            StudentId = 3,
                            SubjectId = 3
                        },
                        new
                        {
                            Id = 9,
                            StudentId = 4,
                            SubjectId = 5
                        },
                        new
                        {
                            Id = 10,
                            StudentId = 4,
                            SubjectId = 7
                        },
                        new
                        {
                            Id = 11,
                            StudentId = 5,
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 12,
                            StudentId = 5,
                            SubjectId = 7
                        });
                });

            modelBuilder.Entity("Interrapidisimo.Microservices.Api.Student.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2026, 2, 4, 15, 54, 53, 185, DateTimeKind.Utc).AddTicks(7173),
                            Email = "andres.galeano@gmail.com",
                            FirstName = "Andres",
                            LastName = "Galeano"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2026, 2, 4, 15, 54, 53, 185, DateTimeKind.Utc).AddTicks(7183),
                            Email = "isabella@gmail.com",
                            FirstName = "Isabella",
                            LastName = "Roche"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2026, 2, 4, 15, 54, 53, 185, DateTimeKind.Utc).AddTicks(7185),
                            Email = "andrea@gmail.com",
                            FirstName = "Andrea",
                            LastName = "Velasco"
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2026, 2, 4, 15, 54, 53, 185, DateTimeKind.Utc).AddTicks(7187),
                            Email = "felipe@gmail.com",
                            FirstName = "Felipe",
                            LastName = "Velasco"
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTime(2026, 2, 4, 15, 54, 53, 185, DateTimeKind.Utc).AddTicks(7189),
                            Email = "danya@gmail.com",
                            FirstName = "Danya",
                            LastName = "Sotelo"
                        });
                });

            modelBuilder.Entity("Interrapidisimo.Microservices.Api.Student.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Credits")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(3);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Subjects", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Credits = 3,
                            Name = "Matematicas",
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 2,
                            Credits = 3,
                            Name = "Fisica",
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 3,
                            Credits = 3,
                            Name = "Quimica",
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 4,
                            Credits = 3,
                            Name = "Biologia",
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 5,
                            Credits = 3,
                            Name = "Historia",
                            TeacherId = 3
                        },
                        new
                        {
                            Id = 6,
                            Credits = 3,
                            Name = "Geografia",
                            TeacherId = 3
                        },
                        new
                        {
                            Id = 7,
                            Credits = 3,
                            Name = "Programacion",
                            TeacherId = 4
                        },
                        new
                        {
                            Id = 8,
                            Credits = 3,
                            Name = "Base de Datos",
                            TeacherId = 4
                        },
                        new
                        {
                            Id = 9,
                            Credits = 3,
                            Name = "Economia",
                            TeacherId = 5
                        },
                        new
                        {
                            Id = 10,
                            Credits = 3,
                            Name = "Estadistica",
                            TeacherId = 5
                        });
                });

            modelBuilder.Entity("Interrapidisimo.Microservices.Api.Student.Entities.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Teachers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Profesor Juan Perez"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Profesor Maria Gomez"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Profesor Carlos Ruiz"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Profesor Ana Torres"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Profesor Luis Herrera"
                        });
                });

            modelBuilder.Entity("Interrapidisimo.Microservices.Api.Student.Entities.Enrollment", b =>
                {
                    b.HasOne("Interrapidisimo.Microservices.Api.Student.Entities.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Interrapidisimo.Microservices.Api.Student.Entities.Subject", "Subject")
                        .WithMany("Enrollments")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Interrapidisimo.Microservices.Api.Student.Entities.Subject", b =>
                {
                    b.HasOne("Interrapidisimo.Microservices.Api.Student.Entities.Teacher", "Teacher")
                        .WithMany("Subjects")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Interrapidisimo.Microservices.Api.Student.Entities.Student", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("Interrapidisimo.Microservices.Api.Student.Entities.Subject", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("Interrapidisimo.Microservices.Api.Student.Entities.Teacher", b =>
                {
                    b.Navigation("Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
